const auth = require('../../middleware/Auth')
module.exports =(app)=>{
    let guide = require('../controller/Guide.controller')
    app.route('/api/guide')
        .get(auth,guide.listGuide)
        .post(guide.createGuide)
    app.route('/api/guide/:id')
        .get(guide.Readguide)
        .put(guide.UpdateGuide)
        .delete(guide.DelGuide)
    // app.route('/api/guide/assign')
    //     .post(auth,guide.Assignment)
    app.get('/api/guideAssign',auth,guide.guideAssign)
    app.get('/api/editAssign',auth,guide.editAssign)
    app.put('/api/cancleAssign/:id',guide.cancleAssign)
    app.param('id',guide.guideById)
}